### ISSUE TITLE
Heroku: LoadError: libgsl.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by skozz** [tomwolfe/heroku-buildpack-gsl-ruby#3]
I can't make it works on Heroku 

```
014-07-23T09:54:43.259797+00:00 app[worker.1]: LoadError: libgsl.so.0: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.0.0/gems/gsl-1.15.3/lib/rb_gsl.so
2014-07-23T09:54:43.260174+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/gsl-1.15.3/lib/gsl.rb:2:in `require'
2014-07-23T09:54:43.260176+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/gsl-1.15.3/lib/gsl.rb:2:in `<top (required)>'
2014-07-23T09:54:43.260178+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/similarity-0.2.5/lib/similarity/corpus.rb:1:in `require'
2014-07-23T09:54:43.260179+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/similarity-0.2.5/lib/similarity/corpus.rb:1:in `<top (required)>'
2014-07-23T09:54:43.260180+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/similarity-0.2.5/lib/similarity.rb:1:in `require'
2014-07-23T09:54:43.260182+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/similarity-0.2.5/lib/similarity.rb:1:in `<top (required)>'
2014-07-23T09:54:43.260183+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
2014-07-23T09:54:43.260184+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
2014-07-23T09:54:43.260186+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
2014-07-23T09:54:43.260187+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
2014-07-23T09:54:43.260188+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
2014-07-23T09:54:43.260190+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
2014-07-23T09:54:43.260191+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
2014-07-23T09:54:43.260192+00:00 app[worker.1]: /app/config/application.rb:12:in `<top (required)>'
2014-07-23T09:54:43.260193+00:00 app[worker.1]: /app/Rakefile:4:in `require'
2014-07-23T09:54:43.260195+00:00 app[worker.1]: /app/Rakefile:4:in `<top (required)>'
```

**Comment by gregory** [comment]
just made 2 buildpack(1.16 and 1.15) for ruby, check this out:  https://github.com/gregory/heroku-gsl-buildpack
